/*
 * ========== !!!! DO NOT ALTER THIS FILE !!!! =======
 * This file is automatically generated by postinstall.js
 * To add/del/modify files listed in this file, 
 * please modify the public files object inside postinstall.js and run node postinstall.js
*/
module.exports = {
	debug_scripts:{
		js :{
			'x3domjs': "/public/js/external/x3dom.js",
			'angularjs': "/public/js/external/angular.js",
			'ammojs': "/public/js/external/ammo.js",
			'angularutilsjs': "/public/js/external/angular-ui-utils.min.js",
			'angularrouterjs': "/public/js/external/angular-ui-router.js",
			'momentjs': "/public/js/external/moment.js",
			'showdownjs': "/public/js/external/showdown.min.js",
			'angularsliderjs': "/public/js/external/slider.js",
			'socketio': "/public/js/external/socket.io.js",
			'angularmaterialjs': "/public/js/external/angular-material.min.js",
			'angularanimatejs': "/public/js/external/angular-animate.min.js",
			'angularariajs': "/public/js/external/angular-aria.min.js",
			'angularsanitizejs': "/public/js/external/angular-sanitize.min.js",
			'dms': "/public/js/external/dms.js",
			'vector3d': "/public/js/external/vector3d.js",
			'latlon-ellipsoidal': "/public/js/external/latlon-ellipsoidal.js",
			'osgridref': "/public/js/external/osgridref.js"
		},
		css :{
			'x3domcss': "/public/css/external/x3dom.css",
			'fontawesomecss': "/public/css/external/font-awesome.min.css",
			'repouicss': "/public/css/ui.css",
			'angularmaterialcss': "/public/css/external/angular-material.min.css",
			'threedrepocss': "/public/css/external/three-d-repo.css"
		}
	},
	prod_scripts:{
		js :{
			'x3domjs': "/public/js/external/x3dom.min.js",
			'angularjs': "/public/js/external/angular.min.js",
			'ammojs': "/public/js/external/ammo.min.js",
			'angularutilsjs': "/public/js/external/angular-ui-utils.min.js",
			'angularrouterjs': "/public/js/external/angular-ui-router.min.js",
			'momentjs': "/public/js/external/moment.min.js",
			'showdownjs': "/public/js/external/showdown.min.js",
			'angularsliderjs': "/public/js/external/slider.min.js",
			'socketio': "/public/js/external/socket.io.min.js",
			'angularmaterialjs': "/public/js/external/angular-material.min.js",
			'angularanimatejs': "/public/js/external/angular-animate.min.js",
			'angularariajs': "/public/js/external/angular-aria.min.js",
			'angularsanitizejs': "/public/js/external/angular-sanitize.min.js",
			'dms': "/public/js/external/dms.min.js",
			'vector3d': "/public/js/external/vector3d.min.js",
			'latlon-ellipsoidal': "/public/js/external/latlon-ellipsoidal.min.js",
			'osgridref': "/public/js/external/osgridref.min.js"
		},
		css :{
			'x3domcss': "/public/css/external/x3dom.min.css",
			'fontawesomecss': "/public/css/external/font-awesome.min.css",
			'repouicss': "/public/css/ui.min.css",
			'angularmaterialcss': "/public/css/external/angular-material.min.css",
			'threedrepocss': "/public/css/external/three-d-repo.min.css"
		}
	}
}