// Generated by Selenium IDE
const { Builder, By, Key } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const assert = require('assert')
const {waitForElementToBeReady , takeScreenshot, delay} = require('./helpers/selenium');

const BASE_URL = 'http://127.0.0.1:8080';
const configuration = { timeout: 15000 };


describe('3drepo.io', function() {
  this.timeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    const args = new chrome.Options().addArguments(['headless','disable-gpu', 'enable-logging']);
  
    driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(args)
      .build();

    try {
        await driver.manage().window().setRect({
          width: 1025,
          height: 950
        });
      } catch (error) {
        console.log('Unable to resize window. Skipping.');
      };

    vars = {}
  })

  afterEach(async function() {
    await driver.quit();
  })

  it('Login', async function() {
    await driver.get((new URL('/login', BASE_URL)).href);

    try {
      await driver.manage().window().setRect({
        width: 1025,
        height: 950
      });
    } catch (error) {
      console.log('Unable to resize window. Skipping.');
    };

    try {
      await (await waitForElementToBeReady(driver, By.name('login'), configuration.timeout)).sendKeys('teamSpace1');

      await (await waitForElementToBeReady(driver, By.name('password'), configuration.timeout)).sendKeys('password');

      // Click login
      await (await waitForElementToBeReady(driver, By.css('button[type=submit]'), configuration.timeout)).click();

      // Closes the 'update available' dialog if its showing
      try {
        await (await waitForElementToBeReady(driver, By.css("[role='dialog'] button"), configuration.timeout)).click();
      } catch (e) {
        // The 'update available' dialog is not there: carry on
      }

      //  Click user menu
      await (await waitForElementToBeReady(driver, By.css("button[aria-label='Toggle main menu']"), configuration.timeout)).click();

      //  Click logout
      await (await waitForElementToBeReady(driver, By.css("[aria-label='Logout']"), configuration.timeout)).click();
    }

    catch(e) {
      await takeScreenshot(driver);
      throw e;
    }
  })
})


