export const CRITERIA_DATA_TYPES = {
	FIELD: 1,
	TEXT: 2,
	NUMBER: 3
};

export const CRITERIA_OPERATORS_TYPES = {
	IS_EMPTY: 'IS_EMPTY',
	IS_NOT_EMPTY: 'IS_NOT_EMPTY',
	IS: 'IS',
	IS_NOT: 'IS_NOT',
	CONTAINS: 'CONTAINS',
	NOT_CONTAINS: 'NOT_CONTAINS',
	EQUALS: 'EQUALS',
	NOT_EQUALS: 'NOT_EQUALS',
	GT: 'GT',
	GTE: 'GTE',
	LT: 'LT',
	LTE: 'LTE',
	IN_RANGE: 'IN_RANGE',
	NOT_IN_RANGE: 'NOT_IN_RANGE',
	EXISTS: 'EXISTS',
	NOT_EXISTS: 'NOT_EXISTS',
	REGEX: 'REGEX'
};

export const CRITERIA_OPERATORS_LABELS = {
	[CRITERIA_OPERATORS_TYPES.IS_EMPTY]: 'is empty',
	[CRITERIA_OPERATORS_TYPES.IS_NOT_EMPTY]: 'is not empty',
	[CRITERIA_OPERATORS_TYPES.IS]: 'is',
	[CRITERIA_OPERATORS_TYPES.IS_NOT]: 'is not',
	[CRITERIA_OPERATORS_TYPES.EXISTS]: 'exists',
	[CRITERIA_OPERATORS_TYPES.NOT_EXISTS]: 'does not exist',
	[CRITERIA_OPERATORS_TYPES.CONTAINS]: 'contains',
	[CRITERIA_OPERATORS_TYPES.NOT_CONTAINS]: 'does not contain',
	[CRITERIA_OPERATORS_TYPES.EQUALS]: 'equals',
	[CRITERIA_OPERATORS_TYPES.NOT_EQUALS]: 'does not equal',
	[CRITERIA_OPERATORS_TYPES.GT]: 'greater than',
	[CRITERIA_OPERATORS_TYPES.GTE]: 'greater or equal to',
	[CRITERIA_OPERATORS_TYPES.LT]: 'less than',
	[CRITERIA_OPERATORS_TYPES.LTE]: 'less or equal to',
	[CRITERIA_OPERATORS_TYPES.IN_RANGE]: 'in range',
	[CRITERIA_OPERATORS_TYPES.NOT_IN_RANGE]: 'not in range',
	[CRITERIA_OPERATORS_TYPES.REGEX]: 'Regex'
};

export const CRITERIA_REQUIRED_VALUES = {
	[CRITERIA_OPERATORS_TYPES.IS_EMPTY]: 0,
	[CRITERIA_OPERATORS_TYPES.IS_NOT_EMPTY]: 0,
	[CRITERIA_OPERATORS_TYPES.IS]: 1,
	[CRITERIA_OPERATORS_TYPES.CONTAINS]: 1,
	[CRITERIA_OPERATORS_TYPES.NOT_CONTAINS]: 1,
	[CRITERIA_OPERATORS_TYPES.EQUALS]: 1,
	[CRITERIA_OPERATORS_TYPES.NOT_EQUALS]: 1,
	[CRITERIA_OPERATORS_TYPES.GT]: 1,
	[CRITERIA_OPERATORS_TYPES.GTE]: 1,
	[CRITERIA_OPERATORS_TYPES.LT]: 1,
	[CRITERIA_OPERATORS_TYPES.LTE]: 1,
	[CRITERIA_OPERATORS_TYPES.IN_RANGE]: 2,
	[CRITERIA_OPERATORS_TYPES.NOT_IN_RANGE]: 2
};

const CRITERIA_FIELD = {
	name: 'Field',
	operators: [{
		label: CRITERIA_OPERATORS_LABELS.EXISTS,
		operator: CRITERIA_OPERATORS_TYPES.IS_NOT_EMPTY
	}, {
		label: CRITERIA_OPERATORS_LABELS.NOT_EXISTS,
		operator: CRITERIA_OPERATORS_TYPES.IS_EMPTY
	}]
};

const CRITERIA_TEXT = {
	name: 'Text',
	operators: [{
		label: CRITERIA_OPERATORS_LABELS.IS,
		operator: CRITERIA_OPERATORS_TYPES.IS
	}, {
		label: CRITERIA_OPERATORS_LABELS.IS_NOT,
		operator: CRITERIA_OPERATORS_TYPES.IS_NOT
	}, {
		label: CRITERIA_OPERATORS_LABELS.CONTAINS,
		operator: CRITERIA_OPERATORS_TYPES.CONTAINS
	}, {
		label: CRITERIA_OPERATORS_LABELS.NOT_CONTAINS,
		operator: CRITERIA_OPERATORS_TYPES.NOT_CONTAINS
	}, {
		label: CRITERIA_OPERATORS_LABELS.REGEX,
		operator: CRITERIA_OPERATORS_TYPES.REGEX
	}]
};

const CRITERIA_NUMBER = {
	name: 'Number',
	operators: [{
		label: CRITERIA_OPERATORS_LABELS.EQUALS,
		operator: CRITERIA_OPERATORS_TYPES.EQUALS
	}, {
		label: CRITERIA_OPERATORS_LABELS.NOT_EQUALS,
		operator: CRITERIA_OPERATORS_TYPES.NOT_EQUALS
	}, {
		label: CRITERIA_OPERATORS_LABELS.GT,
		operator: CRITERIA_OPERATORS_TYPES.GT
	}, {
		label: CRITERIA_OPERATORS_LABELS.LT,
		operator: CRITERIA_OPERATORS_TYPES.LT
	}, {
		label: CRITERIA_OPERATORS_LABELS.IN_RANGE,
		operator: CRITERIA_OPERATORS_TYPES.IN_RANGE
	}, {
		label: CRITERIA_OPERATORS_LABELS.NOT_IN_RANGE,
		operator: CRITERIA_OPERATORS_TYPES.NOT_IN_RANGE
	}]
};

export const CRITERIA_LIST = [
	CRITERIA_FIELD,
	CRITERIA_TEXT,
	CRITERIA_NUMBER
];

export const VALUE_FIELD_TYPES = {
	SINGLE: 'SINGLE',
	RANGE: 'RANGE',
	MULTIPLE: 'MULTIPLE',
	EMPTY: 'EMPTY'
}

export const VALUE_FIELD_MAP = {
	[CRITERIA_OPERATORS_TYPES.CONTAINS]: VALUE_FIELD_TYPES.MULTIPLE,
	[CRITERIA_OPERATORS_TYPES.EQUALS]: VALUE_FIELD_TYPES.MULTIPLE,
	[CRITERIA_OPERATORS_TYPES.EXISTS]: VALUE_FIELD_TYPES.EMPTY,
	[CRITERIA_OPERATORS_TYPES.GT]: VALUE_FIELD_TYPES.SINGLE,
	[CRITERIA_OPERATORS_TYPES.GTE]: VALUE_FIELD_TYPES.SINGLE,
	[CRITERIA_OPERATORS_TYPES.IN_RANGE]: VALUE_FIELD_TYPES.RANGE,
	[CRITERIA_OPERATORS_TYPES.IS]: VALUE_FIELD_TYPES.MULTIPLE,
	[CRITERIA_OPERATORS_TYPES.IS_EMPTY]: VALUE_FIELD_TYPES.EMPTY,
	[CRITERIA_OPERATORS_TYPES.IS_NOT]: VALUE_FIELD_TYPES.MULTIPLE,
	[CRITERIA_OPERATORS_TYPES.IS_NOT_EMPTY]: VALUE_FIELD_TYPES.EMPTY,
	[CRITERIA_OPERATORS_TYPES.LT]: VALUE_FIELD_TYPES.SINGLE,
	[CRITERIA_OPERATORS_TYPES.LTE]: VALUE_FIELD_TYPES.SINGLE,
	[CRITERIA_OPERATORS_TYPES.NOT_CONTAINS]: VALUE_FIELD_TYPES.MULTIPLE,
	[CRITERIA_OPERATORS_TYPES.NOT_EQUALS]: VALUE_FIELD_TYPES.MULTIPLE,
	[CRITERIA_OPERATORS_TYPES.NOT_EXISTS]: VALUE_FIELD_TYPES.EMPTY,
	[CRITERIA_OPERATORS_TYPES.NOT_IN_RANGE]: VALUE_FIELD_TYPES.RANGE,
	[CRITERIA_OPERATORS_TYPES.REGEX]: VALUE_FIELD_TYPES.SINGLE,
}