trigger: none   # manual run only

resources:
  repositories:
    - repository: devops-source
      type: github
      endpoint: 3drepo
      name: 3drepo/DevOps
      ref: refs/heads/ISSUE_1205   # 👈 DevOps branch with Helm changes

variables:
  vmImageName: 'ubuntu-24.04'
  branchName: ISSUE_5657    # 👈 app branch (release name in Helm)
  imageTag: f71d98c3084d12f07f30d55d32d2ef112c04ffcf   # 👈 built image
  customHelmOverride: |
    config.ADDITIONAL_CONFIG=hello

stages:
- stage: Helm
  displayName: Deploy only
  jobs:
    - job: DeployHelmChart
      pool:
        vmImage: $(vmImageName)
      steps:
        - checkout: devops-source   # 👈 pull DevOps repo at ISSUE_1205

        - task: HelmInstaller@1
          displayName: Helm Installer
          inputs:
            helmVersion: '3.10.3'
            installKubectl: true
            kubectlVersion: 'v1.26.3'

        - task: HelmDeploy@0
          displayName: Deploy helm chart
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'stg3drepo'
            namespace: 'default'
            command: 'upgrade'
            chartType: 'Path'
            chartPath: '$(Build.SourcesDirectory)/devops-source/helm/io'
            releaseName: '$(branchName)'
            overrideValues: 'image.tag=$(imageTag),branchName=$(branchName),$(customHelmOverride)'
