trigger:
  batch: true
  branches:
    include:
    - master
    - staging

pr:
  branches:
    include:
    - 'ISSUE_*'  # must quote since "*" is a YAML reserved character; we want a string

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: '3drepo.io'
  containerRegistry: '3drepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile.local.source'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '3drepo-2080'
        repository: '3drepo.io'
        command: 'buildAndPush'
        Dockerfile: '.azure/Docker/Dockerfile.local.source'



