trigger: none

variables:
  vmImageName: 'ubuntu-24.04'
  branchName: ISSUE_5657
  dockerRegistryServiceConnection: '3drepo.azurecr.io'
  imageRepository: '3drepo.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile'
  tag: '$(Build.BuildId)'
  customHelmOverride: |
    config.ADDITIONAL_CONFIG=hello

resources:
  repositories:
    - repository: devops-source
      type: github
      endpoint: 3drepo
      name: 3drepo/DevOps
      ref: refs/heads/ISSUE_1205   # DevOps repo branch with Helm changes

stages:
- stage: BuildAndDeploy
  displayName: Build & Deploy
  jobs:
    - job: BuildAndDeploy
      pool:
        vmImage: $(vmImageName)
      steps:
        # Checkout IO repo (source of Dockerfile)
        - checkout: self

        # Build & push Docker image
        - task: Docker@2
          displayName: Build and push Docker image
          inputs:
            command: buildAndPush
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            containerRegistry: $(dockerRegistryServiceConnection)
            buildContext: $(Build.SourcesDirectory)
            tags: |
              $(Build.SourceBranchName)
              $(Build.SourceVersion)

        # Checkout DevOps repo for Helm chart
        - checkout: devops-source
          path: devops-source
          persistCredentials: true

        # Normalize branch name
        - script: |
            echo '##vso[task.setvariable variable=branchName]'$( echo $BUILD_SOURCEBRANCHNAME | sed "s/_/-/" | awk '{print tolower($0)}' )
          displayName: "Normalize branch name"

        # Helm Installer
        - task: HelmInstaller@1
          displayName: Helm Installer
          inputs:
            helmVersion: '3.10.3'
            installKubectl: true
            kubectlVersion: 'v1.26.3'

        # Deploy Helm chart from DevOps repo ISSUE_1205 branch
        - task: HelmDeploy@0
          displayName: Deploy helm chart
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'stg3drepo'
            namespace: 'default'
            command: 'upgrade'
            chartType: 'Path'
            chartPath: '$(Build.SourcesDirectory)/helm/io'
            releaseName: '$(branchName)'
            overrideValues: 'image.tag=$(Build.SourceVersion),branchName=$(branchName),$(customHelmOverride)'
