trigger:
  batch: true
  branches:
    include:
    - master
    - staging

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-24.04'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3drepo.azurecr.io'
  imageRepository: '3drepo.io'
  containerRegistry: '3drepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile'
  tag: '$(Build.BuildId)' # not used currently
  DOCKER_BUILDKIT: 1
  branchName: master
  group: tests-group

stages:
- stage: Build
  displayName: Container
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
      # fetchDepth: 1   # the depth of commits to ask Git to fetch, but 3 mins to get depth1 vs 1 minute 20 to get all.

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(Build.SourceBranchName)
          $(Build.SourceVersion)
