trigger:
  batch: true
  branches:
    include:
    - master
    - staging

pr:
  branches:
    include:
    - master
    - staging
    - 'ISSUE_*'

resources:
  repositories:
  - repository: devops
    type: github
    endpoint: 3drepo   # <-- GitHub service connection in Azure DevOps
    name: 3drepo/DevOps
    ref: refs/heads/$(DEVOPS_BRANCH)

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-24.04'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3drepo.azurecr.io'
  imageRepository: '3drepo.io'
  containerRegistry: '3drepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile'
  tag: '$(Build.BuildId)' # not used currently
  DOCKER_BUILDKIT: 1
  branchName: master
  group: tests-group
  customHelmOverride: |
    config.ADDITIONAL_CONFIG=hello

  # Default DevOps branch (can override at queue time)
  DEVOPS_BRANCH: ISSUE_1205

stages:
- stage: Build
  displayName: Container
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self  # self = IO repo (where this YAML lives)

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(Build.SourceBranchName)
          $(Build.SourceVersion)

- stage: Helm
  displayName: Deploy
  jobs:
    - job: DeployHelmChart
      pool:
        vmImage: $(vmImageName)
      displayName: Deploy
      steps:

      # 1️⃣ Checkout the DevOps repo branch with your Helm changes
      - checkout: devops
        path: devops-source
        persistCredentials: true

      # 2️⃣ Install Helm
      - task: HelmInstaller@1
        displayName: Helm Installer
        inputs:
          helmVersion: '3.10.3'
          installKubectl: true
          kubectlVersion: 'v1.26.3'
          checkLatestHelmVersion: false

      # 3️⃣ Determine branch name for release
      - script: |
          if [[ "$SYSTEM_PULLREQUEST_SOURCEBRANCH" != "" ]]; then
            echo "##vso[task.setvariable variable=branchName]$( echo $SYSTEM_PULLREQUEST_SOURCEBRANCH | sed "s/_/-/" | awk '{print tolower($0)}' )"
          else
            echo "##vso[task.setvariable variable=branchName]$( echo $BUILD_SOURCEBRANCHNAME | sed "s/_/-/" | awk '{print tolower($0)}' )"
          fi
        displayName: Set branchName variable

      # 4️⃣ Get default Helm values file
      - task: Bash@3
        displayName: Get default Helm values file
        inputs:
          targetType: 'inline'
          script: |
            curl -u ${TESTS_USER}:${TESTS_PASSWORD} '$(helm-3drepo-io-defaults)' --output $(System.ArtifactsDirectory)/values.yaml
        env:
          helm-3drepo-io-defaults: $(helm-3drepo-io-defaults)
          TESTS_USER: $(TESTS_USER)
          TESTS_PASSWORD: $(TESTS_PASSWORD)

      # 5️⃣ Package the Helm chart from your branch
      - task: Bash@3
        displayName: Package Helm chart
        inputs:
          targetType: 'inline'
          script: |
            helm package $(Build.SourcesDirectory)/devops-source/helm/io --destination $(Build.ArtifactsDirectory)
      
      # 6️⃣ Deploy the packaged chart
      - task: HelmDeploy@0
        displayName: Deploy Helm chart
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'stg3drepo'
          namespace: 'default'
          command: 'upgrade'
          chartType: 'Path'
          chartPath: '$(Build.ArtifactsDirectory)/io-*.tgz'
          releaseName: '$(branchName)'
          overrideValues: 'image.tag=$(Build.SourceVersion),branchName=$(branchName),$(customHelmOverride)'
          valueFile: $(System.ArtifactsDirectory)/values.yaml
          waitForExecution: true
