trigger:
  batch: true
  branches:
    include:
    - master
    - staging
    - helm

pr:
  branches:
    include:
    - master
    - staging
    - helm

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8775ee4b-0b4d-40f5-b4fd-c9c74e4c5cac'
  imageRepository: '3drepo.io'
  containerRegistry: '3drepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile'
  tag: '$(Build.BuildId)'
  DOCKER_BUILDKIT: 1

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: short Hash
  workingDirectory: $(Build.SourcesDirectory)


- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          $(Build.SourceBranchName)
          $(Build.SourceVersion)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
    - job: HelmInstall
      displayName: Install Helm
      steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '3.3.1'
          installKubectl: true
          kubectlVersion: '1.16.6-beta.0'

      - task: HelmDeploy@0
        displayName: Helm Repo Add 
        inputs:
          command: repo
          arguments: add 3drepo https://3drepo.github.io/DevOps/

      - task: HelmDeploy@0
        displayName: Helm Repo update 
        inputs:
          command: repo
          arguments: update

    - job: HelmDeploy
      displayName: Helm Deployment
      steps: 
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'AWS EKS D5-default-1599670380350'
          namespace: 'default'
          command: 'upgrade'
          chartType: 'Name'
          chartName: '3drepo/3drepo-io'
          chartVersion: '0.2.2'
          releaseName: '${Build.SourceBranchName}'
          overrideValues: 'image.tag=$(tag),branchName=$(Build.SourceBranchName)'
          recreate: true