trigger: none

variables:
  # Agent VM image name
  # TOUCHED
  vmImageName: 'ubuntu-20.04'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3drepo.azurecr.io'
  imageRepository: '3drepo.io'
  containerRegistry: '3drepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile'
  tag: '$(Build.BuildId)' # not used currently
  DOCKER_BUILDKIT: 1
  isMaster: $[eq(variables.branchName, 'master')]
  isStaging: $[eq(variables.branchName, 'staging')]
  willDelete: $[and(eq(variables.isMaster, 'false'), eq(variables.isStaging, 'false'))]

stages:
- stage: Helm
  displayName: Destroy
  condition: eq(variables.willDelete,'true')
  jobs:
    - job: DestroyHelmChart
      pool:
        vmImage: $(vmImageName)
      variables:
      - name: DECODE_PERCENTS
        value: false
      displayName: Destroy
      steps:
      - checkout: none
      - task: HelmInstaller@1
        displayName: Helm Installer
        inputs:
          helmVersion: '3.10.3'
          installKubectl: true
          kubectlVersion: 'v1.26.3'
          checkLatestHelmVersion: false

      - task: HelmDeploy@0
        displayName: Remove instance
        continueOnError: true
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'stg3drepo'
          namespace: 'default'
          command: 'uninstall'
          arguments: '$(branchName)'
