trigger: none

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-20.04'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8775ee4b-0b4d-40f5-b4fd-c9c74e4c5cac'
  imageRepository: '3drepo.io'
  containerRegistry: '3drepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.azure/Docker/Dockerfile'
  tag: '$(Build.BuildId)' # not used currently
  DOCKER_BUILDKIT: 1
  isMaster: $[eq(variables.branchName, 'master')]
  isStaging: $[eq(variables.branchName, 'staging')]
  willDelete: $[and(eq(variables.isMaster, 'false'), eq(variables.isStaging, 'false'))]

stages:
- stage: Helm
  displayName: Destroy
  condition: eq(variables.willDelete,'true')
  jobs:
    - job: DestroyHelmChart
      pool:
        vmImage: $(vmImageName)
      variables:
      - name: DECODE_PERCENTS
        value: false
      displayName: Destroy
      steps:
      - checkout: none
      - task: HelmInstaller@1
        displayName: Helm Installer
        inputs:
          helmVersion: '3.8.0'
          installKubectl: true
          kubectlVersion: 'v1.19.1'
          checkLatestHelmVersion: false
      
      - task: Kubernetes@1
        displayName: Kubernetes Authentication
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'AWS EKS D5-default-1599670380350'
          command: 'login'

      - task: Bash@3
        displayName: Test to see if instance exists
        condition: eq(variables.willDelete,'true')
        inputs:
          script: |
            helm status "$branchName" ; [ $? -eq 1 ] && echo '##vso[task.setvariable variable=willDelete]false'
          targetType: 'inline'
        env:
          branchName: '$(branchName)'

      - task: HelmDeploy@0
        displayName: Remove instance
        condition: eq(variables.willDelete,'true')
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'AWS EKS D5-default-1599670380350'
          namespace: 'default'
          command: 'uninstall'
          arguments: '$(branchName)'