import { library } from '@fortawesome/fontawesome-svg-core';
import { faArrowsAltH } from '@fortawesome/free-solid-svg-icons/faArrowsAltH';
import { faCopy } from '@fortawesome/free-solid-svg-icons/faCopy';
import { faDrawPolygon } from '@fortawesome/free-solid-svg-icons/faDrawPolygon';
import { faEraser } from '@fortawesome/free-solid-svg-icons/faEraser';
import { faEye } from '@fortawesome/free-solid-svg-icons/faEye';
import { faFilter } from '@fortawesome/free-solid-svg-icons/faFilter';
import { faHandPaper } from '@fortawesome/free-solid-svg-icons/faHandPaper';
import { faHelicopter } from '@fortawesome/free-solid-svg-icons/faHelicopter';
import { faSortAmountDown } from '@fortawesome/free-solid-svg-icons/faSortAmountDown';
import { faSortAmountUp } from '@fortawesome/free-solid-svg-icons/faSortAmountUp';
import { faStreetView } from '@fortawesome/free-solid-svg-icons/faStreetView';
import { faTint } from '@fortawesome/free-solid-svg-icons/faTint';

library.add(faEraser);
library.add(faEye);
library.add(faFilter);
library.add(faTint);
library.add(faHandPaper);
library.add(faSortAmountUp);
library.add(faSortAmountDown);
library.add(faHelicopter);
library.add(faArrowsAltH);
library.add(faDrawPolygon);
library.add(faCopy);
library.add(faStreetView);
