name: Chat Operations Dispatch
on:
  issue_comment:
    types: [ created ]
jobs:
  chatOperations:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          commands: |
            deploy
            destroy
          issue-type: pull-request  