name: Deploy To Staging

# The deployment system now needs environment variable setting to gather the custom variables, 
# it's below, search for customHelmOverride       

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: write
  deployments: write

on:
  push:
    branches:
      - 'master'
      - 'staging'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - 'master'
      - 'staging'

  repository_dispatch:
    types: [ deploy-command ]

jobs:
  get-details:
    name: Get PR and Issue Details
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.commitMsgParser.outputs.issue-number }}
      issue-content-id: ${{ steps.commitMsgParser.outputs.issue-content-id }}
      deployment-id: ${{ steps.githubdeployment.outputs.deployment_id }}
    steps:
      - name: Extract Issue Number from PR
        uses: 3drepo/extract-pr-information@v1
        with:
          pr: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: commitMsgParser

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: githubdeployment
        with:
          token: '${{ github.token }}'
          sha: '${{ github.sha }}'
          transient-environment: true
          auto-inactive: true
          initial-status: 'in_progress'
          environment: issue-${{ steps.commitMsgParser.outputs.issue-number }}

  build-images:
    name: Build Container Images
    needs: [ get-details ]
    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    concurrency:
      # If a previous run is ongoing with the same head_ref (it's a run on the
      # same PR) then cancel it to save time. If it isn't a PR, only cancel the
      # previous run if it's on the same commit SHA. This prevents a run for a
      # commit push from cancelling a previous commit push's build, since we
      # want an image built and tagged for each commit.
      group: build-images-${{ matrix.image }}-${{ github.head_ref || github.sha }}
      cancel-in-progress: true
    permissions:
      contents: read  # Read the repo contents.
     
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
        - io
        # - io-debug

        include:
        - image: io
          dockerfile: .azure/Docker/Dockerfile
          platforms: linux/amd64 #,linux/arm64
          image-name: "3drepo.azurecr.io/3drepo.io"
          tag: ${{ github.sha }}
          release-tag: latest

        # example of how to add an additional build to the matrix.
        
        # - image: io-debug
        #   dockerfile: .azure/Docker/Dockerfile_debug
        #   platforms: linux/amd64,linux/arm64
        #   image-name: "${{ secrets.REGISTRY_LOGIN_SERVER }}/3drepo.io"
        #   tag: ${{ github.sha }}-debug
        #   release-tag: debug

    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: 'Log into ACR'
      uses: azure/docker-login@v1
      with:
        login-server: 3drepo.azurecr.io
        username: ${{  env.REGISTRY_USERNAME }}
        password: ${{  env.REGISTRY_PASSWORD }}

    # Build and push with Docker.
    - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
      with:
        platforms: ${{ matrix.platforms }}

    - uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.4.1
      with:
        driver-opts: |
          image=moby/buildkit:master

    - name: Docker meta
      id: docker-tag-creation
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
      with:
        # list of Docker images to use as base name for tags
        images: |
          "3drepo.azurecr.io/3drepo.io"
        # Docker tags based on the following events/attributes
        tags: |
          type=raw,value=ISSUE_${{ needs.get-details.outputs.issue-number }}
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
          type=sha,format=long,prefix=

    - uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
      id: build-and-push
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platforms }}
        push: true # ${{ github.event_name != 'pull_request' }} # Only push if not a PR.
        tags: ${{ steps.docker-tag-creation.outputs.tags }}
        labels: ${{ steps.docker-tag-creation.outputs.labels }}
        no-cache-filters: certs
        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
        cache-from: type=registry,ref=3drepo.azurecr.io/3drepo.io:buildcache,compression=zstd
        cache-to: type=registry,ref=3drepo.azurecr.io/3drepo.io:buildcache,mode=max

    - name: Update deployment status (failure)
      if: failure() && needs.get-details.outputs.deployment-id
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        state: 'failure'
        deployment-id: ${{ needs.get-details.outputs.deployment-id }}

  deploy-branch:
    name: Deploy Pipeline
    runs-on: ubuntu-latest
    needs: [ get-details, build-images ]
    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Checkout Default Helm values
      run: curl "https://${ACCESS_TOKEN}@${PATH_TO_VALUES}" --output ./values.yaml
      env:
        ACCESS_TOKEN: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
        PATH_TO_VALUES: ${{ secrets.DEVOPS_HELM_VALUES }}

    - name: Set Custom Values
      run: |
        echo "customHelmOverride=${customHelmOverride}" >> $GITHUB_OUTPUT
      id: custom_values
      env:
        customHelmOverride: config.ADDITIONAL_CONFIG=hello   #   example of setting an additional setting in helm.
        
        # you can swap for this version to change to it's own rabbitmq 
        # customHelmOverride: config.APP_QUEUE_DNS=issue-${{ needs.get-details.outputs.issue-number }}-rabbitmq

    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.3
      if: needs.get-details.outputs.issue-number
      with:
        aws-region: eu-west-2
        cluster-name: ${{ secrets.AWS_EKS_CLUSTER }}
        config-files: ./values.yaml
        chart-path: 3drepo/io
        namespace: default
        name: issue-${{ needs.get-details.outputs.issue-number }}
        values: "image.tag=${{ github.sha }},branchName=issue-${{ needs.get-details.outputs.issue-number }},${{ steps.custom_values.outputs.customHelmOverride }}"
        chart-repository: https://3drepo.github.io/DevOps/
        version: 5.0.7
        atomic: true
        helm-wait: true
        timeout: 30m

    - name: Update deployment status (success)
      if: success() && needs.get-details.outputs.deployment-id
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        state: 'success'
        auto-inactive: true
        deployment-id: ${{ needs.get-details.outputs.deployment-id }}
        environment-url: https://issue-${{ needs.get-details.outputs.issue-number }}.dev.3drepo.io/?sha=${{ github.sha }}
        environment: issue-${{ needs.get-details.outputs.issue-number }}

    - name: Update deployment status (failure)
      if: failure() && needs.get-details.outputs.deployment-id
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        state: 'failure'
        deployment-id: ${{ needs.get-details.outputs.deployment-id }}
