name: On PR closed
on:
  pull_request:
    types: [closed]
jobs:
  tagOnPRMerge:
    name: Tag merged issues as In staging if applicable
    runs-on: ubuntu-latest
    steps:
      - name: Is PR merged into staging
        uses: carmenfan/extract-issue-number-from-PR-merge@v1.1
        with:
          pr: ${{ github.event.number }}
          base: staging
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: commitMsgParser
      - name: Apply in staging label
        if: steps.commitMsgParser.outputs.issue-number
        uses: carmenfan/any-issue-labeller@v1.1
        with:
          issue-number: ${{ steps.commitMsgParser.outputs.issue-number }}
          label: 'in staging'
          github-token: ${{ secrets.GITHUB_TOKEN }}
